
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author phúc
 */
public class QuanLyMonHocSinhVien extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyMonHocSinhVien
     */
    public QuanLyMonHocSinhVien() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        dataInComboBox(); 
        jRadioButton1.setSelected(true); 
        getTable();
    }

    public void getTable(){
        try {   
            DBAccess ac = new DBAccess();
            ResultSet rs =  ac.Query("select * from Tbl_QuanLyMonHocSinhVien");
            while(rs.next()){ 
                String ID = rs.getString("ID");
                String MaSV = rs.getString("MaSV");
                String TenSV = rs.getString("TenSV"); 
                String MaMon = rs.getString("MaMon");
                String TenMon = rs.getString("TenMon"); 
                String HocKy = rs.getString("HocKy");
                String Diem = rs.getString("Diem"); 
                String TrangThai = rs.getString("TrangThai");
                String MaGV = rs.getString("MaGV"); 
                
                String table[] = {ID, MaSV, TenSV, MaMon, TenMon, Diem, HocKy, MaGV, TrangThai};
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                model.addRow(table);
            }
        } catch (Exception ex) { 
            JOptionPane.showMessageDialog(null, ex.toString(),"Loi",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID: ");

        jLabel2.setText("Mã SV:");

        jLabel3.setText("Tên SV : ");

        jLabel4.setText("Mã Môn:");

        jLabel5.setText("Tên Môn :");

        jLabel6.setText("Học Kỳ : ");

        jLabel7.setText("Điểm :");

        jLabel8.setText("Trạng Thái : ");

        jLabel9.setText("Mã Giảng Viên : ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("QUẢN LÝ MÔN HỌC SINH VIÊN ");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Đậu");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Trượt");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã SV", "Tên SV", "Mã Môn", "Tên Môn", "Điểm ", "Học Kỳ", "Mã Giảng Viên", "Trạng Thái"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Chọn Mã Sinh Viên ---" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Chọn Tên Sinh Viên ---" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Chọn Mã Môn ---" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Chọn Tên Môn ---" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Chọn Học Kỳ ---" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Chọn Mã Giảng Viên ---" }));

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jComboBox1, 0, 178, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField6)
                            .addComponent(jComboBox4, 0, 178, Short.MAX_VALUE)
                            .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox6, 0, 177, Short.MAX_VALUE)))
                .addGap(219, 219, 219))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel8)
                        .addGap(38, 38, 38)
                        .addComponent(jRadioButton1)
                        .addGap(31, 31, 31)
                        .addComponent(jRadioButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton1)
                        .addGap(86, 86, 86)
                        .addComponent(jButton2)
                        .addGap(92, 92, 92)
                        .addComponent(jButton3)
                        .addGap(94, 94, 94)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ID =  jTextField1.getText();
        String MaSV = jComboBox1.getSelectedItem().toString();
        String TenSV = jComboBox2.getSelectedItem().toString();
        String MaMon = jComboBox3.getSelectedItem().toString();
        String TenMon = jComboBox4.getSelectedItem().toString();
        String Diem = jTextField6.getText();
        String HocKy = jComboBox5.getSelectedItem().toString();
        String MaGV = jComboBox6.getSelectedItem().toString(); 
        String TrangThai;
        if(jRadioButton1.isSelected()){
            TrangThai = "Dau";
        }else{
            TrangThai = "Truot";
        }
        try {
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            MyConnection connect = new MyConnection();
            Connection con =  connect.getConnection();
            String insertData = "insert into Tbl_QuanLyMonHocSinhVien values(?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(insertData);  
            pst.setString(1, ID);
            pst.setString(2, MaSV);
            pst.setString(3, TenSV);
            pst.setString(4, MaMon);
            pst.setString(5, TenMon);
            pst.setString(6, HocKy);
            pst.setString(7, Diem);
            pst.setString(8,TrangThai );
            pst.setString(9, MaGV);

            pst.executeUpdate();
            getTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here: 
         JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() ); 
            jTextField1.setText(source.getModel().getValueAt(row,0).toString());  
            jComboBox1.setSelectedItem(source.getModel().getValueAt(row,1));  
            jComboBox2.setSelectedItem(source.getModel().getValueAt(row,2));  
            jComboBox3.setSelectedItem(source.getModel().getValueAt(row,3));  
            
             
            jComboBox4.setSelectedItem(source.getModel().getValueAt(row,4)); 
            jTextField6.setText(source.getModel().getValueAt(row,5).toString()); 
            
            jComboBox5.setSelectedItem(source.getModel().getValueAt(row,6));   
            jComboBox6.setSelectedItem(source.getModel().getValueAt(row,7));  
            if(source.getModel().getValueAt(row,8).toString().compareTo("Dau") == 7){
                jRadioButton1.setSelected(true);
            }else{
                jRadioButton2.setSelected(true);
            }
            
            jTextField1.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
    public boolean checkExist(String Id){
           DBAccess ac = new DBAccess();
           if(Id != ""){
              String query = "select * from Tbl_MonHoc where ID = '" + Id + "'";
               try {
                   ResultSet rs =  ac.Query(query);
                   if(rs.next()){
                       return true;
                   }
               } catch (Exception e) {
                   JOptionPane.showMessageDialog(null, "Something Error");
               }
           } 
           return false; 
       }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String ID = jTextField1.getText();  
        try {
                if(checkExist(ID)){
                    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                    model.setRowCount(0);
                    
                    String updateData = "UPDATE Tbl_QuanLyMonHocSinhVien SET MaSV =  ?, TenSV = ?, MaMon = ?, TenMon = ?, HocKy = ?, Diem = ?, TrangThai = ?, MaGV = ? WHERE ID = '" + ID + "'"; 
                    MyConnection connect = new MyConnection();
                    Connection con =  connect.getConnection();
                    PreparedStatement pst = con.prepareStatement(updateData);  
                    
                    pst.setString(1, jComboBox1.getSelectedItem().toString());
                    pst.setString(2, jComboBox2.getSelectedItem().toString());
                    pst.setString(3, jComboBox3.getSelectedItem().toString());
                    pst.setString(4, jComboBox4.getSelectedItem().toString());
                    
                    
                    pst.setString(5, jComboBox5.getSelectedItem().toString());
                    
                    pst.setString(6, jTextField6.getText());
                    
                    pst.setString(8, jComboBox6.getSelectedItem().toString()); 
                    if(jRadioButton1.isSelected()){
                       pst.setString(7, "Dau"); 
                    }else{
                        pst.setString(7, "Truot"); 
                    }
                    pst.execute();  
                    getTable();
                }  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String ID = jTextField1.getText();  
        try {
                if(checkExist(ID)){
                    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                    model.setRowCount(0); 
                    String deleteData = "Delete from Tbl_QuanLyMonHocSinhVien WHERE ID = '" + ID + "'"; 
                    MyConnection connect = new MyConnection();
                    Connection con =  connect.getConnection();
                    PreparedStatement pst = con.prepareStatement(deleteData);  
                    pst.execute();  
                    getTable();
                }  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Delete Fail");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(""); 
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        jComboBox6.setSelectedIndex(0);
        jTextField6.setText(""); 
        jTextField1.setEnabled(true);
        jRadioButton1.setSelected(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    public void dataInComboBox(){
        getData("Tbl_SinhVien", "MaSV", jComboBox1);
        getData("Tbl_SinhVien", "TenSV", jComboBox2); 
        getData("Tbl_MonHoc", "MaMon", jComboBox3);
        getData("Tbl_MonHoc", "TenMon", jComboBox4);
        getData("Tbl_MonHoc", "HocKy", jComboBox5);
        getData("Tbl_GiangVien", "MaGV", jComboBox6); 
    }
     public void getData(String nameTable, String query, JComboBox a){
        try {   
            DBAccess ac = new DBAccess();
            ResultSet rs =  ac.Query("select " + query + " from " + nameTable); 
            while(rs.next()){ 
                a.addItem(rs.getString(query));
            }
        } catch (Exception ex) { 
            JOptionPane.showMessageDialog(null, ex.toString(),"Loi",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHocSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHocSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHocSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHocSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyMonHocSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
