
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author phúc
 */
public class ThongKe extends javax.swing.JFrame {

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        dataInComboBox();
        getTable("select * from Tbl_QuanLyMonHocSinhVien, Tbl_GiangVien where Tbl_QuanLyMonHocSinhVien.MaGV = Tbl_GiangVien.MaGV");
    }
    public void dataInComboBox(){
        getData("Tbl_MonHoc", "HocKy", jComboBox1);
        getData("Tbl_SinhVien", "MaSV",jComboBox2);
        getData("Tbl_GiangVien", "MaGV", jComboBox3);
        getData("Tbl_MonHoc", "MaMon",jComboBox4);
    }
    public void getData(String nameTable, String query, JComboBox a){
        try {   
            DBAccess ac = new DBAccess();
            ResultSet rs =  ac.Query("select " + query + " from " + nameTable); 
            while(rs.next()){ 
                a.addItem(rs.getString(query));
            }
        } catch (Exception ex) { 
            JOptionPane.showMessageDialog(null, ex.toString(),"Loi",JOptionPane.ERROR_MESSAGE);
        }
    }
    public void getTable(String query){
        try {   
            DBAccess ac = new DBAccess();
            ResultSet rs =  ac.Query(query);
            while(rs.next()){ 
                String MaSV = rs.getString("MaSV");
                String TenSV = rs.getString("TenSV");
                String MaMon = rs.getString("MaMon");
                String TenMon = rs.getString("TenMon");
                String HocKy = rs.getString("HocKy");
                String Diem = rs.getString("Diem");
                String TrangThai = rs.getString("TrangThai");
                String MaGV = rs.getString("MaGV");
                String TenGV = rs.getString("TenGV");
                String SDTGV = rs.getString("SDTGV"); 
                String emailGV = rs.getString("emailGV"); 
                
                String table[] = {MaSV, TenSV, MaMon, TenMon, HocKy, Diem, TrangThai, MaGV, TenGV, SDTGV, emailGV};
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                model.addRow(table);
            }  
        } catch (Exception ex) { 
            JOptionPane.showMessageDialog(null, ex.toString(),"Loi",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("THỐNG  KÊ BÁO CÁO SINH VIÊN");

        jLabel2.setText("Học Kỳ :");

        jLabel3.setText("Mã SV : ");

        jLabel4.setText("Mã GV :");

        jLabel5.setText("Mã MH : ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Chọn Học Kỳ ---" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Chọn Mã Sinh Viên ---" }));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Chọn Mã Giáo Viên ---" }));
        jComboBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox3MouseClicked(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Chọn Mã Môn Học ---" }));
        jComboBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox4MouseClicked(evt);
            }
        });

        jButton1.setText("Tìm Kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xuất File Excel");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sinh Viên", "Tên Sinh Viên ", "Mã Môn", "Tên Môn", "Học Kỳ", "Diem", "Trạng Thái", "Mã Giảng Viên ", "Tên Giảng Viên", "SĐT GV", "Email Giảng Viên"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String query = "Select * from Tbl_QuanLyMonHocSinhVien, Tbl_GiangVien where Tbl_QuanLyMonHocSinhVien.MaGV = Tbl_GiangVien.MaGV ";
        String a1 = jComboBox1.getSelectedItem().toString();
        String a2 = jComboBox2.getSelectedItem().toString();
        String a3 = jComboBox3.getSelectedItem().toString();
        String a4 = jComboBox4.getSelectedItem().toString();
        
        int value1 = jComboBox1.getSelectedIndex();
        int value2 = jComboBox2.getSelectedIndex();
        int value3 = jComboBox3.getSelectedIndex();
        int value4 = jComboBox4.getSelectedIndex();

        if(value1 != 0 && value2 != 0 && value3 != 0 && value4 != 0){ 
             query += " and HocKy = '" + a1 + "' and MaSV = '" + a2 + "' and Tbl_GiangVien.MaGV = '" + a3 +"' and MaMon = '" + a4 +"'"; 
        }else{ 
            if(value1 != 0 && value2 != 0 && value3 != 0){
                query += " and HocKy = '" + a1 + "' and MaSV = '" + a2 + "' and Tbl_GiangVien.MaGV = '" + a3 +"'"; 
            }else if( value2 != 0 && value3 != 0 && value4 != 0){
                query += " and MaSV = '" + a2 + "' and Tbl_GiangVien.MaGV = '" + a3 + "' and MaMon = '" + a4 +"'"; 
            }else if(value3 != 0 && value4 != 0 && value1 != 0 ){
                query += " and HocKy = '" + a1 + "' and Tbl_GiangVien.MaGV = '" + a3 + "' and MaMon = '" + a4 +"'"; 
            }else if(value1 != 0 && value2 != 0 && value4 != 0){
                query += " and HocKy = '" + a1 + "' and MaSV = '" + a2 + "'and MaMon = '" + a4 +"'"; 
            }else{
                if(value1 != 0 && value2 != 0 ){
                    query += " and HocKy = '" + a1 + "' and MaSV = '" + a2 + "'"; 
                }else if(value2 != 0 && value3 != 0){
                    query += " and MaSV = '" + a2 + "' and Tbl_GiangVien.MaGV = '" + a3 + "'"; 
                }else if(value2 != 0 && value4 != 0){
                    query += " and MaSV = '" + a2 + "' and MaMon = '" + a4 +"'"; 
                }else if(value3 != 0 && value4 != 0){
                    query += " and Tbl_GiangVien.MaGV = '" + a3 +"' and MaMon = '" + a4 +"'"; 
                }else if(value1 != 0 && value3 != 0){
                    query += " and HocKy = '" + a1 + "' and Tbl_GiangVien.MaGV = '" + a3 +"'"; 
                }else if(value1 != 0 && value4 != 0){
                    query += " and HocKy = '" + a1 + "' and MaMon = '" + a4 +"'"; 
                }else{
                    if(value1 != 0){
                        query += " and HocKy = '" + a1 + "'";
                    }else if(value2 != 0){
                         query += " and MaSV = '" + a2 + "'"; 
                    }else if(value3 != 0){
                         query += " and Tbl_GiangVien.MaGV = '" + a3 + "'"; 
                    }else if(value4 != 0){
                         query += " and MaMon = '" + a4 +"'"; 
                    }else{
                        query = "loiiiii";   
                    }
                }
            }
        }   
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        getTable(query);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here: 
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseClicked
        // TODO add your handling code here: 
    }//GEN-LAST:event_jComboBox3MouseClicked

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        // TODO add your handling code here: 
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jComboBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MouseClicked
        // TODO add your handling code here: 
    }//GEN-LAST:event_jComboBox4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
